eo_dataflow_ui/apps/downloader_admin/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.listdownload, name='listdownload'),
#    url(r'^test$', views.test, name='test'),
    url(r'^new$', views.new, name='new'),
    url(r'^nbActivatedFile$', views.getActivatedNbFile, name='nbActivatedFile'),
    url(r'^nbDesactivatedFile$', views.getDesactivatedNbFile, name='nbDeactivatedFile'),
    url(r'^nbTestFile$', views.getTestNbFile, name='nbTestFile'),
    url(r'^help$', views.help, name='help'),
    #url(r'^filterdownloads/(?P<pattern>\S+)$', views.filter_downloads, name='filterdownloads'),
    url(r'^createdownload/(?P<download_id>\S+)$', views.create_and_edit_download, name='createdownload'),

    url(r'^(?P<xml_filename>\S+)/(?P<download_id>\S+)/define_test_file$', views.define_test_file, name='define_test_file'),
    url(r'^(?P<xml_filename>\S+)/(?P<download_id>\S+)/save_test_file$', views.save_test_file, name='save_test_file'),
    url(r'^(?P<download_id>\S+)/testlog$', views.display_test_log, name='testlog'),
    url(r'^(?P<download_id>\S+)/synchrolog$', views.display_synchro_log, name='synchrolog'),
    url(r'^(?P<download_id>\S+)/logfile$', views.display_download_log, name='display_download_log'),

    url(r'^(?P<xml_filename>\S+)/(?P<download_id>\S+)/copy_as_file', views.copy_as_file, name='copy_as_file'),

    url(r'^change_queue$', views.new_queue, name='change_queue'),

    url(r'^(?P<xml_filename>\S+)/(?P<download_id>\S+)/reload_from_file', views.reload_from_file, name='reload_from_file'),

    url(r'^synchro/listing/download/(?P<download_id>\S+)', views.move_synchro_listing_to_download, name='move_synchro_listing_to_download'),
    url(r'^synchro/listing/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.display_synchro_listing, name='display_synchro_listing'),
    url(r'^synchro/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.status_synchro, name='status_synchro'),
    url(r'^test/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.status_test, name='status_test'),

    url(r'^nbfile/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.nb_file_synchro, name='nb_file_synchro'),
    url(r'^date/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.date_synchro, name='date_synchro'),
    url(r'^checksynchro/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.check_synchro, name='checksynchro'),
    #url(r'^runsynchro/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.run_synchro, name='runsynchro'),

    url(r'^(?P<xml_filename>\S+)/save$', views.save, name='save'),

    url(r'^(?P<xml_filename>\S+)/activate$', views.activate, name='activate'),
    url(r'^(?P<xml_filename>\S+)/desactivate$', views.desactivate, name='deactivate'),
    url(r'^remove/(?P<xml_filename>\S+)/(?P<download_id>\S+)$', views.remove, name='remove'),
    url(r'^(?P<xml_filename>\S+)/delete$', views.delete, name='delete'),
    url(r'^(?P<xml_filename>\S+)/modetest$', views.modetest, name='modetest'),
    url(r'^(?P<xml_filename>\S+)/redownloaderror', views.redownload_error, name='redownload_error'),
    url(r'^(?P<xml_filename>\S+)/countdownloaderror', views.count_download_error, name='count_download_error'),

    url(r'^(?P<xml_filename>\S+)$', views.editdownload, name='edit'),
]

eo_dataflow_ui/urls.py
import os

from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.contrib.auth import urls as auth_urls

from eo_dataflow_ui.apps.downloader_admin import urls as dladm_urls

admin.autodiscover()

url_prefix = os.environ.get("URL_PREFIX", "")

urlpatterns = [
    url(r"%sadmin" % url_prefix, include(admin.site.urls)),
    url(r"^%saccount/" % url_prefix, include(auth_urls)),
    url(r"%s" % url_prefix, include(dladm_urls, namespace="dladmin")),

]

urlpatterns += staticfiles_urlpatterns()

eo_dataflow_ui/templates/navbar.html
{% load static %} {% load xml_data_tags %}
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
			<table>
				<tr>
					<td width="50%">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
							</button>
							<a class="navbar-brand" href="{% url 'dladmin:listdownload' %}">eo-dataflow</a>
						</div>
					</td>
					<td width="50%">
						<form name="queues" action="{% url 'dladmin:change_queue' %}" method="post">
							{% csrf_token %}
							<select id="new_queue" name="new_queue" onchange="this.form.submit()">
								{% get_active_queues %}
							</select>
						</form>
					</td>
				</tr>
			</table>

		<!-- /.nav-collapse -->
	</div>
	<script type="text/javascript">
		function moveToMonitoring() {
			goToNav("moveToMonitoring");
		}

		function moveToStatistics() {
			goToNav("moveToStatistics");
		}

		function moveToManage() {
			goToNav("moveToManage");
		}

		function goToNav(direction) {
			if (direction == "moveToMonitoring") {
				$('#isMonitoring').addClass("active");
				$('#isStatistics').removeClass("active");
				$('#isManage').removeClass("active");
			} else if (direction == "moveToStatistics") {
				$('#isMonitoring').removeClass("active");
				$('#isStatistics').addClass("active");
				$('#isManage').removeClass("active");
			} else if (direction == "moveToManage") {
				$('#isMonitoring').removeClass("active");
				$('#isStatistics').removeClass("active");
				$('#isManage').addClass("active");
			} else {
				$('#isMonitoring').removeClass("active");
				$('#isStatistics').removeClass("active");
				$('#isManage').addClass("active");
			}
		}

	</script>
</div>